# install commandline utils
brew 'ag'
brew 'awsebcli'
brew 'cmake'
brew 'fzf'
brew 'httpie'
brew 'lua'
brew 'mongodb'
brew 'node'
brew 'nvm'
brew 'rbenv'
brew 'rbenv-gem-rehash'
brew 'ruby-build'
brew 'pandoc'
brew 'tree'
brew 'tmux'
brew 'vim'
brew 'wget'
brew 'youtube-dl'

# install homebrew-cask
brew 'caskroom/cask/brew-cask'

# install apps
cask '1password'
cask 'adobe-creative-cloud'
cask 'alfred'
cask 'bettertouchtool'
cask 'cyberduck'
cask 'dash'
cask 'dropbox'
cask 'flux'
cask 'google-chrome'
cask 'heroku-toolbelt'
cask 'imageoptim'
cask 'iterm2'
cask 'macdown'
cask 'mjolnir'
cask 'ngrok'
cask 'plug'
cask 'pixel-winch'
cask 'private-internet-access'
cask 'psequel'
cask 'seil'
cask 'skitch'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'transmission'
cask 'xquartz'
cask 'vlc'
